### ISSUE TITLE
proxy.txt文件需要填写什么ip了？

### ISSUE THREAD

**Issue by tahitimoon** [lumaoren2024/nodepay_bot.2.0#1]
proxy.txt文件需要填写什么ip了？

**Comment by lumaoren2024** [comment]
你自己的代理ip：http://127.0.0.1:7890 例如这样！

**Comment by tahitimoon** [comment]
如果自己电脑本机，需要填写吗？nodepay挂机收益最大，是一个账号挂多个ip，还是同一个ip挂几个账号了？

**Comment by lumaoren2024** [comment]
一般挂机都是建议内网跑，服务器跑没必要。建议1号多ip,女巫规则谁都不明白，只能尽量避免！
多个号的话，尽量跑的时候ip别重复！

**Comment by tahitimoon** [comment]
对ip有要求吗，最好使用美国ip？楼主有挂grass，不知道grass能用这个方式么？

**Comment by tahitimoon** [comment]
代理ip支持账号密码的那种吗？

**Comment by lumaoren2024** [comment]
支持的，标准写法就可以了！

**Comment by tahitimoon** [comment]
好的 感谢解答。grass您这边有挂过吗？不知道是否可以用相同得方式去挂

lumaoren2024 ***@***.***>于2024年10月31日 周四15:01写道：
